---
port: "8080"
host: localhost
max_elements_before_flush: 10000
compaction_frequency_in_ms: 5000
wal_path: "wal.aof"
udp_port: "1053"
udp_buffer_size: 4096
num_of_partitions: 10
directory: "/home/avashmitra/projects/midDB/data"
bloom_capacity: 100000
bloom_error_rate: 0.0001
